### PR TITLE
Decaffeinate to ES6

### LINKED ISSUE #2: Package won't build (fails at `npm ci`)

### LINKED ISSUE #3: Add GitHub actions for CI
We need GitHub actions for CI enabled to check for lint, tests, coverage etc.

### PR DESCRIPTION
**Pull request by jankapunkt**
At first we need to decaffeinate the project before we can start improvements.

- Not many people understand coffeescript
- ES6 is stable and widely supported
- there should be no errors during conversion from coffee to es6
- we can skip the whole gulp processing
- we can use mocha+puppeteer for tests to ensure we don't break anything
- we can use prettier for linting and formatting

### CODE REVIEW

**Comment by jankapunkt** [comment]
Tests are running again, however this is not release ready, there are the following things to be done (in sequence; prioritized):

- all tests currently run in `node` env but we need to run all other tests also using puppeteer to simulate minimongo usage within browser
- I commented out  one line that requires `navigator` which we need to integrate with `puppeteer`
- tests should be restructured, they are currently hard to read and use often `this.` to attach things to the mocha environment but since we can easily use modules we should restructure tests
- test coverage is currently not very high and we might introduce regressions
- CI should be added using GitHub actions, fortunately I have already existing setups that will work so this is just one PR away
- rest of the code should be converted to es6 as well as decaffeinate did not convert to es6 100% this should also take the autogenerated comments from decaffeinate into consideration
- dependencies need to be updated and vulnerabilities need to be resolved
- meteor react native integration tests need to be added


@TheRealNate can you give me permission to open issues so we can keep track of things left todo?

**Comment by not-ai-yet** [comment]
@jankapunkt enabled issues. I'm also finishing up NPM setup shortly.

**Comment by jankapunkt** [comment]
The recent push started the GitHub actions and they passed successfully, therefore this would also fix #3 and #2

**Comment by jankapunkt** [comment]
@TheRealNate once this is merged the npm publish workflow should also pass, since `npm ci` is now working

**Comment by not-ai-yet** [comment]
@jankapunkt Thats awesome! Once you merge to master and create a new release the action should automatically publish the package to `@meteorrn/minimongo`.

**Pull request merged**
