### PR TITLE
Refactor to es6

### LINKED ISSUE #6: Complete migration to ES6
The `decaffeinate` tool (see #1) did not 100% convert all parts to ES6:

- there are many `var` statements left
- there are many older Array Methods
- `lodash` is often used but many of it's functions can be replaced by native ES6 counterparts
- decaffeinate added comments on the top of the files where still some unconverted things or no-op code

This issue requires #5 first to be completed in order to prevent undetected regression

### PR DESCRIPTION
**Pull request by jankapunkt**
This pr moves all code to ES6 and removes outdated dependencies where possible.

### CODE REVIEW

**Comment by jankapunkt** [comment]
Hey @TheRealNate @diavrank I completely updated this library and replaced lodash with native ES6

If this gets released we can update the core to use this instead of the 6 years old minimongo and have nearly all vulnerabilities removed.

**Comment by jankapunkt** [comment]
@TheRealNate can you take a look at this? This is required to fix all these lodash issues that arise when install `@meteorrn/core` and `minimongo-cache` is somewhat abandoned so this is now our new updated minimongo cache with lodash replaced by native ES6.

Once this is published, for example as `@meteorrn/minimongo` then we can finalize the current PR on `@meteorrn/core` (https://github.com/meteorrn/meteor-react-native/pull/99)

**Review by not-ai-yet — APPROVED** [review]
Looks good to me! Merge when ready

**Comment by jankapunkt** [comment]
Thank you @TheRealNate can you publish it to npm? We can then include it in https://github.com/meteorrn/meteor-react-native/pull/99

**Comment by not-ai-yet** [comment]
@jankapunkt Done. Theres a GH action setup to auto publish when a new release is declared, so you should be able to use that in the future.

**Pull request merged**
